<?php

namespace Siga98\Helpers\Test\Features;

use Siga98\Helpers\Test\BaseCase;
use Siga98\Helpers\ByteHelpers;

class ByteHelpersTest extends BaseCase
{
	private $byteArray;
	
	public function setUp(): void
	{
		parent::setUp(); // TODO: Change the autogenerated stub
		
		$this->byteArray = unpack('C*', 'hello');
	}
	
	/**
	 * @test
	 */
	public function string2Hex(): void
	{
		$this->assertEquals(ByteHelpers::string2Hex('hello'), '68656c6c6f');
	}
	
	/**
	 * @test
	 */
	public function byteArray2String(): void
	{
		$this->assertEquals(ByteHelpers::byteArray2String($this->byteArray), 'hello');
		
	}
	
	/**
	 * @test
	 */
	public function byteArray2Hex(): void
	{
		$this->assertEquals(ByteHelpers::byteArray2Hex($this->byteArray), '68656c6c6f');
		
	}
	
	/**
	 * @test
	 */
	public function hex2ByteArray(): void
	{
		$this->assertEquals(ByteHelpers::hex2ByteArray('68656c6c6f'), $this->byteArray);
		
	}
	
	/**
	 * @test
	 */
	public function hex2String(): void
	{
		$this->assertEquals(ByteHelpers::hex2String('68656c6c6f'), 'hello');
		
	}
	
	/**
	 * @test
	 */
	public function string2ByteArray(): void
	{
		$this->assertEquals(ByteHelpers::string2ByteArray('hello'), $this->byteArray);
	}
}
