<?php

namespace Siga98\Helpers\Test\Features;

use Siga98\Helpers\StringHelper;
use Siga98\Helpers\Test\BaseCase;

class StringHelperTest extends BaseCase
{
	private $testString;
	
	public function setUp(): void
	{
		parent::setUp(); // TODO: Change the autogenerated stub
		$this->testString = 'Hello World';
	}
	
	/**
	 * @test
	 */
	public function containsWord(): void
	{
		$contains = StringHelper::contains($this->testString, 'orld');
		
		$this->assertTrue($contains, $this->generateMessage($contains));
	}
	
	/**
	 * @test
	 */
	public function endsWith(): void
	{
		$endsWith = StringHelper::endsWith($this->testString, 'orld');
		
		$this->assertTrue($endsWith, $this->generateMessage($endsWith));
	}
	
	/**
	 * @test
	 */
	public function camelCase(): void
	{
		$camelCase = StringHelper::camelCase($this->testString, ' ');
		
		$this->assertEquals($camelCase, 'HelloWorld', $this->generateMessage($camelCase));
	}
	
	/**
	 * @test
	 */
	public function startWith(): void
	{
		$startWith = StringHelper::startWith($this->testString, 'Hell');
		
		$this->assertTrue($startWith, $this->generateMessage($startWith));
	}
}
